### ISSUE TITLE
Error with get_complementary_idx_distance_decay

### ISSUE THREAD

**Issue by m-barbosa** [learningmatter-mit/surface-sampling#3]
Hello @xiaochendu,

I encountered an error while running Si_111_5x5 tutorial and another system I'm working with (using Tersoff potential). The GaN tutorial seems to be working. The error appears randomly after 30-100 sweeps on multiple machines.

 File "/home/barbosa/softwares/surface-sampling/mcmc/mcmc.py", line 380, in run
    sweep_result = self.sweep(i=i)  # TODO change to .step
                   ^^^^^^^^^^^^^^^
  File "/home/barbosa/softwares/surface-sampling/mcmc/mcmc.py", line 280, in sweep
    accept = self.step_canonical(iter_num=run_idx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barbosa/softwares/surface-sampling/mcmc/mcmc.py", line 225, in step_canonical
    event = Exchange(self.surface, proposal, criterion)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barbosa/softwares/surface-sampling/mcmc/events/event.py", line 132, in __init__
    self.action = self.proposal.get_action()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barbosa/softwares/surface-sampling/mcmc/events/proposal.py", line 163, in get_action
    site1_idx, site2_idx, site1_ads, site2_ads = get_complementary_idx(
                                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barbosa/softwares/surface-sampling/mcmc/slab.py", line 202, in get_complementary_idx
    site1_idx, site2_idx = (
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/barbosa/softwares/surface-sampling/mcmc/slab.py", line 203, in <genexpr>
    random.choices(curr_ads[x], weights=w, k=1)[0]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barbosa/miniconda3/envs/vssr/lib/python3.11/random.py", line 509, in choices
    raise ValueError('Total of weights must be greater than zero')
ValueError: Total of weights must be greater than zero

**Comment by xiaochendu** [comment]
Hi @m-barbosa, thanks for posting this issue.

Can I confirm that you are using the latest version on `master`?

It seems like one of `weights1` or `weights2` sums to 0. I'm curious what `type1`, `type2`, `weights1`, `weights2` are at here?
https://github.com/learningmatter-mit/surface-sampling/blob/2b5f8a16647f3a6d69d39bf872c9e36220bde181/mcmc/slab.py#L185-L186

If you can run the code again, set the logger to DEBUG: `logger.setLevel(logging.DEBUG)` at the start of the Jupyter notebook and add 
```python
logger.debug("weights1 %s, weights2 %s", weights1, weights2)
``` 
to `mcmc/slab.py` to log the weights.

**Comment by m-barbosa** [comment]
Yes, I'm using the latest version. Here's the output of the log file
```
11:26:32 - mcmc.slab | DEBUG: current ads {'O': [11, 18, 39], 'None': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43]}
11:26:32 - mcmc.slab | DEBUG: in `get_complementary_idx` using per atom energies
11:26:32 - mcmc.slab | DEBUG: per atom energies are [  0.      0.      0.      0.     46.833  45.035  43.834  41.838  39.846
  36.847  35.665  32.855  31.54   28.863  27.76   24.871  23.785  20.395
  15.897  16.747  15.767  10.889   7.978   4.904   3.849   0.907   0.
   3.088   2.848   7.701   9.535  13.878  16.785  19.077  23.126  24.059
  27.953  29.623  31.775  33.061  35.379  37.061  40.105  42.062  45.225
  47.06   50.575  52.023  56.569  58.973  62.865  65.915  71.755  71.059
  75.448  77.06   81.482  83.06   84.271  85.063  88.397  89.068  94.515
  96.119 101.405 103.08  106.655 109.085 111.414 113.089 117.209 119.122
 122.645 125.103 127.995 130.362 134.385 136.372 139.239 141.122 144.747
 148.535 151.355 153.135 153.137 154.142 166.173 167.175 170.18  171.183
 176.193 175.191 182.184 181.203 188.219 187.216 191.225 191.225 195.235
 196.238 201.25  202.253 203.256 206.265 211.277 212.281 215.289 214.288
 213.289 222.311 225.32  225.321 229.332 230.337 233.345 233.349 237.359
 237.363 238.369  54.845  54.837  51.842  48.905  46.833  45.035  43.834
  41.838  39.846  36.847  35.665  32.855  31.54   28.863  27.76   24.871]
11:26:32 - mcmc.slab | DEBUG: temperature is 0.1
11:26:32 - mcmc.slab | DEBUG: boltzmann weights are [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
11:26:32 - mcmc.slab | DEBUG: Length of curr_ads[type1]: 3
11:26:32 - mcmc.slab | DEBUG: Length of weights1: 3
11:26:32 - mcmc.slab | DEBUG: weights1 [0. 0. 0.], weights2 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1]
```

I have also attached the log file.
[mc.log](https://github.com/user-attachments/files/16639603/mc.log)

**Comment by xiaochendu** [comment]
I see, the Boltzmann weights of the O atoms seem to be too small, such that it rounds to 0 in `weights1`. Can you add a small value to:
https://github.com/learningmatter-mit/surface-sampling/blob/2b5f8a16647f3a6d69d39bf872c9e36220bde181/mcmc/slab.py#L88
,such that `boltzmann_weights` can't be 0?, e.g., 
```
boltzmann_weights = softmax(np.array(per_atom_energies) / temperature) + 1e-3
```

**Comment by xiaochendu** [comment]
Also in my experience, energy-based weights didn't help much with sampling. I only added them to the tutorial for demonstration purpose. You can turn off energy-based weights with
```
sampling_settings = {
    "require_per_atom_energies": False,
}
```

**Comment by m-barbosa** [comment]
I disabled the energy-based weights, and it seems like the code is running without any other problems. Thanks for your help @xiaochendu.
